project:
  type: website 
output-dir: /docs

website:
  title: Project 2
  navbar:
    right:
      - icon: github
        href: https://math241s24.github.io/project-02-harpergusemma/
    left:
      - text: "Project"
        href: index.qmd
      - text: "Proposal"
        href: proposal.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "About"
        href: about.qmd
      - text: "Shiny App"
        href: shinyapp.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
  

