```{r, message=FALSE, warning=FALSE}


# Load necessary libraries
library(tidyverse)
library(tidytext)
library(textdata)

```


```{r}
salmon <- read_csv("salmondata/rawsalmon.csv")


salmon <- salmon %>% rename(species = `Species Name`,
                            num_fish = `Number Of Fish (estimated)`,
                            land_weight = `Landed Weight (lbs)`,
                            whole_weight = `Whole Weight (lbs)`,
                            num_permit = `Permit Count`,
                            num_processor = `Processor Count`,
                            num_vessel = `Vessel Count`)
write.csv(salmon, "salmondata/salmon.csv")
```

```{r}
ggplot(salmon, aes(x = Year, y = num_fish)) +
  geom_line(stat = "identity", aes(color = species))
```

```{r}
fishes <- data.frame(
  legislature = c(18, 19, 20, 21, 22, 23, 24, 25, 26, 27), 
  fishcount = c(88, 133, 280, 149, 120, 54, 161, 91, 31, 22), 
  year = c(1993, 1995, 1997, 1999, 2001, 2003, 2005, 2007, 2009, 2011)
)

sockeye <- salmon %>%
  filter(species == "Sockeye Salmon")

fishsockeye <- right_join(fishes, sockeye, by = c("year" = "Year"))
view(fishsockeye)
```



```{r}
fishandgame <- read.csv("fish_and_game.csv")
fishandgame <- fishandgame %>%
  mutate(Year = case_when(
    Legislature == 33 ~ 2023,
    Legislature == 32 ~ 2021,
    Legislature == 31 ~ 2019,
    Legislature == 30 ~ 2017,
    Legislature == 29 ~ 2015,
    Legislature == 28 ~ 2013,
    Legislature == 27 ~ 2011,
    Legislature == 26 ~ 2009,
    Legislature == 25 ~ 2007,
    Legislature == 24 ~ 2005,
    Legislature == 23 ~ 2003,
    Legislature == 22 ~ 2001,
    Legislature == 21 ~ 1999,
    Legislature == 20 ~ 1997,
    Legislature == 19 ~ 1995,
    Legislature == 18 ~ 1993,
    Legislature == 17 ~ 1991,
    Legislature == 16 ~ 1989,
    Legislature == 15 ~ 1987,
    Legislature == 14 ~ 1985,
  ))

```

```{r}

fishandgame <- fishandgame %>%
  mutate(FULL_TEXT = tolower(FULL_TEXT)) %>%
  mutate(FULL_TEXT = gsub("[[:punct:]]", "", FULL_TEXT),
         FULL_TEXT = str_replace_all(FULL_TEXT, "\\b\\d+\\b", ""),
        FULL_TEXT = str_replace_all(FULL_TEXT, "\\b\\w*\\d+\\w*\\b", ""))


 tokenized_fishandgame <- fishandgame %>%
  unnest_tokens(word, FULL_TEXT)
 
 data("stop_words")
 stopfishandgame <- tokenized_fishandgame %>%
   anti_join(stop_words)
 


salmontextanalysisdf <- inner_join(stopfishandgame, salmon, by = "Year")


threshold <- 50000

salmontextanalysisdf %>%
  count(word, sort = TRUE) %>%
  filter(n > threshold) %>%
  ggplot(aes(y = fct_reorder(word, n), x = n, fill = log(n))) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Frequency of words in Alaksa Department of Fish and Game bills",
    subtitle = "Words occurring more than 50,000 times",
    y = NULL, x = NULL
  )


```

