---
title: "Untitled"
output: html_document
date: "2024-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
```


```{r}
legis <- read_csv("fish_and_game.csv")
view(legis)
legis_line <- legis$FULL_TEXT[7] %>%
  str_split("(?<=\\.)\\s*") %>% # specify the end-of-line character(s)
  pluck(1) 
legis_7 <- legis_line %>%
  str_subset("fish")
view(legis_7)

```


```{r}
combined_legis <- legis %>%
  group_by(Legislature) %>%
  summarise(Combined_Text = paste(FULL_TEXT, collapse = " ! "))

lineee <- combined_legis$Combined_Text[10] %>%
  str_split("(?<=\\.)\\s*") %>% # specify the end-of-line character(s)
  pluck(1) 
legis_1 <- lineee %>%
  str_subset("fish")
length(legis_1)


```

```{r}
fishes <- data.frame(
  legislature = c(18, 19, 20, 21, 22, 23, 24, 25, 26, 27), 
  fishcount = c(88, 133, 280, 149, 120, 54, 161, 91, 31, 22), 
  year = c(1993, 1995, 1997, 1999, 2001, 2003, 2005, 2007, 2009, 2011)
)
plot <- ggplot(data = fishes, aes(x = legislature, y = fishcount)) + 
  geom_line() +
  scale_x_continuous(breaks = c(18, 19, 20, 21, 22, 23, 24, 25, 26, 27)) +
  labs(
    title = "Times 'fish' is mentioned in Alaska legislature from 1993-2012", 
    y = "'fish' mentioned", 
    x = "Legislature number"
  )
plot
```


```{r}
salmon <- read_csv("salmondata/salmon.csv")
view(salmon)
```

```{r}
legis <- read_csv("fish_and_game.csv")
leng <- length(legis$Legislature)

getti <- function(word){
  word_freq <- c()
  for (i in 1:leng){ 
    legis_line <- legis$FULL_TEXT[i] %>%
    str_split("(?<=\\.)\\s*") %>% # specify the end-of-line character(s)
    pluck(1) 
    word_freq_i <- legis_line %>%
    str_subset(word) %>%
    length()
    #message(word_freq_i) #only to check it works
    word_freq <- append(word_freq, word_freq_i)
  }
  return(word_freq)
}

legis_word <- legis %>%
  mutate(fish = getti("[F/f]ish")) %>%
  mutate(fisheries = getti("[F/f]isher[ies/y]")) %>%
  mutate(permit = getti("[P/p]ermit")) %>%
  mutate(vessel = getti("[V/v]essel")) %>%
  mutate(salmon = getti("[S/s]almon")) %>%
  mutate(limit = getti("[L/l]imit")) 
legis_word_longer <- legis_word %>% 
  select(-FULL_TEXT) %>%
  pivot_longer(c('fish', 'fisheries', 'permit', 'vessel', 'salmon', 'limit'), names_to = "word", values_to = "times_mentioned") %>%
  mutate(Year = Legislature) %>%
  mutate(Year = case_when(
    Legislature == 33 ~ 2023,
    Legislature == 32 ~ 2021,
    Legislature == 31 ~ 2019,
    Legislature == 30 ~ 2017,
    Legislature == 29 ~ 2015,
    Legislature == 28 ~ 2013,
    Legislature == 27 ~ 2011,
    Legislature == 26 ~ 2009,
    Legislature == 25 ~ 2007,
    Legislature == 24 ~ 2005,
    Legislature == 23 ~ 2003,
    Legislature == 22 ~ 2001,
    Legislature == 21 ~ 1999,
    Legislature == 20 ~ 1997,
    Legislature == 19 ~ 1995,
    Legislature == 18 ~ 1993,
    Legislature == 17 ~ 1991,
    Legislature == 16 ~ 1989,
    Legislature == 15 ~ 1987,
    Legislature == 14 ~ 1985
  ))
```

```{r}
wordplot <- ggplot(data = legis_word_longer, aes(x = Year, y = times_mentioned, fill = word)) +
  geom_bar(position='stack', stat='identity') +
  theme_minimal() + 
  labs(
    title = "Frequency of Keywords in Alaska State Legislature by Year", 
    x = "Year", 
    y = "Frequency"
  )
wordplot
```

```{r}
yearly_word <- legis_word_longer %>%
  group_by(Year, word) %>%
  summarise(count = sum(times_mentioned))
glimpse(yearly_word)
```
```{r}
yearlyplot <- ggplot(data = yearly_word, aes(x = Year, y = count, color = word)) +
  geom_line() +
  theme_minimal() + 
  labs(
    title = "Frequency of Keywords in Alaska State Legislature by Year", 
    x = "Year", 
    y = "Frequency"
  )
yearlyplot
```


```{r}
scaled_legis_word <- legis_word %>%
  select(-FULL_TEXT) %>% 
  mutate(fish = scale(fish), 
         fisheries = scale(fisheries), 
         limit = scale(limit), 
         permit = scale(permit), 
         salmon = scale(salmon), 
         vessel = scale(vessel)
  ) %>%
  pivot_longer(c('fish', 'fisheries', 'permit', 'vessel', 'salmon', 'limit'), names_to = "word", values_to = "times_mentioned") %>%
  mutate(Year = Legislature) %>%
  mutate(Year = case_when(
    Legislature == 33 ~ 2023,
    Legislature == 32 ~ 2021,
    Legislature == 31 ~ 2019,
    Legislature == 30 ~ 2017,
    Legislature == 29 ~ 2015,
    Legislature == 28 ~ 2013,
    Legislature == 27 ~ 2011,
    Legislature == 26 ~ 2009,
    Legislature == 25 ~ 2007,
    Legislature == 24 ~ 2005,
    Legislature == 23 ~ 2003,
    Legislature == 22 ~ 2001,
    Legislature == 21 ~ 1999,
    Legislature == 20 ~ 1997,
    Legislature == 19 ~ 1995,
    Legislature == 18 ~ 1993,
    Legislature == 17 ~ 1991,
    Legislature == 16 ~ 1989,
    Legislature == 15 ~ 1987,
    Legislature == 14 ~ 1985
  ))

scaleplot <- ggplot(data = scaled_legis_word, aes(x = Year, y = times_mentioned, fill = word)) +
  geom_bar(position='stack', stat='identity') +
  theme_minimal() + 
  labs(
    title = "Frequency of Keywords in Alaska State Legislature by Year", 
    x = "Year", 
    y = "Frequency"
  )
scaleplot
```



