---
title: "Bristol Bay Salmono"
subtitle: "Project 2"
author: "Emma Campbell, Harper Lethin, Gus Compton"
title-slide-attributes:
  data-slide-number: none
format: revealjs
editor: visual
execute:
  echo: false
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(tidymodels)
library(openintro)
library(mdsr)
library(mosaicData)
library(shiny)
library(bslib)
library(ggExtra)
```

```{r}
#| label: setup
#| include: false

# For better figure resolution
knitr::opts_chunk$set(
  fig.retina = 3, 
  dpi = 300, 
  fig.width = 6, 
  fig.asp = 0.618, 
  out.width = "70%"
  )
```

```{r}
#| label: load-data
#| include: false
salmon <- read_csv("salmondata/salmon.csv")
```

```{r}
#| label: Shiny App
#| include: true

ui <- page_sidebar(
  sidebar = sidebar(
    varSelectInput("xvar", "X variable", salmon, selected = "Year"),
    varSelectInput("yvar", "Y variable", salmon, selected = "num_fish"),
    checkboxGroupInput(
      "species", "Filter by species",
      choices = unique(salmon$species), 
      selected = unique(salmon$species)
    ),
    hr(), # Add a horizontal rule
    checkboxInput("by_species", "Show species", TRUE),
  ),
  plotOutput("distPlot")
)

server <- function(input, output, session) {
  subsetted <- reactive({
    req(input$species)
    salmon |> filter(species %in% input$species)
  })

  output$distPlot <- renderPlot({
    p <- ggplot(subsetted(), aes(!!input$xvar, !!input$yvar)) + list(
      theme(legend.position = "bottom"),
      if (input$by_species) aes(fill = species),
      geom_histogram(stat = "identity")
    )


    p
  }, res = 100)
}

shinyApp(ui, server)
```
